### ISSUE TITLE
The script is scanning only the ip range 192.168.0.X

### ISSUE THREAD

**Issue by fs0c131y** [fs0c131y/ESFileExplorerOpenPortVuln#1]
If the victim's ip is 192.168.1.X for example, the script will not work.

**Comment by painca** [comment]
I know about backdoor a long time, you can download files by use ..:59777/sdcard/text.txt

**Comment by fs0c131y** [comment]
Thank you! Can you add the corresponding changes in the README too?

**Comment by kelu27** [comment]
It's done! Thx u!

**Comment by fs0c131y** [comment]
Thank you for your contribution!
