### ISSUE TITLE
import json

### ISSUE THREAD

**Issue by ghost** [fs0c131y/ESFileExplorerOpenPortVuln#9]
why you import json? you not use it.

**Comment by fs0c131y** [comment]
json is used in the sanitize_json method

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/38254691/51306965-55317d00-1a60-11e9-989e-71d1875cf511.png)
maybe use _json.loads_?

**Comment by fs0c131y** [comment]
Nope because their json is malformed

**Comment by ghost** [comment]
Why then import json?
